{
 "title": "BWT Perla",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Restwasser",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mlitre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "capacitycolumn1_ml_dh/hardnessin_dh",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wasser behandelt (heute)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    { "expr": "watertreatedcurrentday_l", "legendFormat": " " }
   ]
  },
  {
   "title": "Wasser behandelt (heute)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "watertreatedcurrentday_l ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gesamtmenge verbraucht",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "blendedwatersincesetup_l/1000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gesamtmenge behandelt",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "watersincesetup_l/1000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Regenerationen Insgesamt",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "regenerationcountsincesetup", "legendFormat": " " }
   ]
  },
  {
   "title": "Regenerationsanzahl",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "regenerationcountsincesetup", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Verbrauchtes Regenerativ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    { "expr": "regenerativsincesetup_g", "legendFormat": " " }
   ]
  },
  {
   "title": "Salztabletten Füllstand in %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "regenerativlevel", "legendFormat": " " }
   ]
  },
  {
   "title": "Salztabletten Füllstand in %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "regenerativlevel", "legendFormat": "__auto" }
   ]
  }
 ]
}